title: Academia-Industry Collaboration
description: At SIGCOMM'24, we held the non-paper session "Academia-Industry Collaboration" to share the stories behind an acamedia-industry collaborations.
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman